# Header
menu:
  首页: /Cheetah/
  归档: /Cheetah/archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: